package bears

var (
	Bears = [...]string{
		Aisle.Name(),
		Barold.Name(),
		Beardo.Name(),
		Bluebear.Name(),
		Charlise.Name(),
		Cheri.Name(),
		Chester.Name(),
		Chow.Name(),
		Cupcake.Name(),
		Curt.Name(),
		Dozer.Name(),
		Grizzly.Name(),
		Groucho.Name(),
		Ike.Name(),
		Judy.Name(),
		June.Name(),
		Klaus.Name(),
		Kody.Name(),
		Maple.Name(),
		Marty.Name(),
		Megan.Name(),
		Murphy.Name(),
		Nate.Name(),
		Olive.Name(),
		Paula.Name(),
		Pekoe.Name(),
		Pinky.Name(),
		Poko.Name(),
		Poncho.Name(),
		Pudge.Name(),
		Stitches.Name(),
		Tammy.Name(),
		Teddy.Name(),
		Tutu.Name(),
		Ursala.Name(),
		Vladimir.Name()}
)
