package species

// order
const (
	accipitriformes  string = "Accipitriformes"
	anseriformes     string = "Anseriformes"
	anura            string = "Anura"
	artiodactyla     string = "Artiodactyla"
	calumbiformes    string = "Calumbiformes"
	carnivora        string = "Carnivora"
	caudata          string = "Caudata"
	charadriiformes  string = "Charadriiformes"
	columbiformes    string = "Columbiformes"
	crocodylia       string = "Crocodylia"
	diprotodontia    string = "Diprotodontia"
	eulipotyphla     string = "Eulipotyphla"
	galliformes      string = "Galliformes"
	lagomorpha       string = "Lagomorpha"
	octopoda         string = "Octopoda"
	pelecaniformes   string = "Pelecaniformes"
	perissodactyla   string = "Perissodactyla"
	pilosa           string = "Pilosa"
	primates         string = "Primates"
	proboscidea      string = "Proboscidea"
	rodentia         string = "Rodentia"
	sphenisciformes  string = "Sphenisciformes"
	squamata         string = "Squamata"
	strigiformes     string = "Strigiformes"
	struthioniformes string = "Struthioniformes"
	testudines       string = "Testudines"
)
