package species

// genus
const (
	alligator      string = "Alligator"
	ambystoma      string = "Ambystoma"
	bos            string = "Bos"
	camelus        string = "Camelus"
	canis          string = "Canis"
	capra          string = "Capra"
	castor         string = "Castor"
	chlamydosaurus string = "Chlamydosaurus"
	equus          string = "Equus"
	felis          string = "Felis"
	gallus         string = "Gallus"
	giraffa        string = "Giraffa"
	gorilla        string = "Gorilla"
	hippopotamus   string = "Hippopotamus"
	macropus       string = "Macropus"
	meleagris      string = "Meleagris"
	mus            string = "Mus"
	nyctereutes    string = "Nyctereutes"
	odobenus       string = "Odobenus"
	ovis           string = "Ovis"
	panthera       string = "Panthera"
	pavo           string = "Pavo"
	pelecanus      string = "Pelecanus"
	phascolarctos  string = "Phascolarctos"
	raphus         string = "Raphus"
	rangifer       string = "Rangifer"
	struthio       string = "Struthio"
	sus            string = "Sus"
	tapirus        string = "Tapirus"
	vicugna        string = "Vicugna"
	vulpes         string = "Vulpes"
)
