package species

// family
const (
	accipitridae    string = "Accipitridae"
	agamidae        string = "Agamidae"
	alligatoridae   string = "Alligatoridae"
	ambystomatidae  string = "Ambystomatidae"
	anatidae        string = "Anatidae"
	bovidae         string = "Bovidae"
	camelidae       string = "Camelidae"
	canidae         string = "Canidae"
	castoridae      string = "Castoridae"
	cervidae        string = "Cervidae"
	chamaeleonidae  string = "Chamaeleonidae"
	cricetidae      string = "Cricetidae"
	columbidae      string = "Columbidae"
	elephantidae    string = "Elephantidae"
	equidae         string = "Equidae"
	erinaceidae     string = "Erinaceidae"
	felidae         string = "Felidae"
	giraffidae      string = "Giraffidae"
	hippopotamidea  string = "Hippopotamidea"
	hominidae       string = "Hominidae"
	laridae         string = "Laridae"
	leporidae       string = "Leporidae"
	macropodidae    string = "Macropodidae"
	mephitidae      string = "Mephitidae"
	muridae         string = "Muridae"
	mustelidae      string = "Mustelidae"
	odobenidae      string = "Odobenidae"
	otariidae       string = "Otariidae"
	pelecanidae     string = "Pelecanidae"
	phascolarctidae string = "Phascolarctidae"
	phasianidae     string = "Phasianidae"
	rhinocerotidae  string = "Rhinocerotidae"
	sciuridae       string = "Sciuridae"
	spheniscidae    string = "Spheniscidae"
	struthionidae   string = "Struthionidae"
	suidae          string = "Suidae"
	talpidae        string = "Talpidae"
	tapiridae       string = "Tapiridae"
	testudinidae    string = "Testudinidae"
	ursidae         string = "Ursidae"
)
