package villagers

var (
	Cats = [...]string{
		Ankha.Name(),
		Blanca.Name(),
		Bob.Name(),
		Felicity.Name(),
		Felyne.Name(),
		Kabuki.Name(),
		Kaitlin.Name(),
		Katie.Name(),
		Katt.Name(),
		KidCat.Name(),
		Kiki.Name(),
		Kitty.Name(),
		Lolly.Name(),
		Meow.Name(),
		Merry.Name(),
		Mitzi.Name(),
		Moe.Name(),
		Monique.Name(),
		Olivia.Name(),
		Pierre.Name(),
		Punchy.Name(),
		Purrl.Name(),
		Raymond.Name(),
		Rosie.Name(),
		Rover.Name(),
		Rudy.Name(),
		Stinky.Name(),
		Tabby.Name(),
		Tangy.Name(),
		Tom.Name()}
)
